events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # UI — served at root
        location / {
            proxy_pass http://eta-flow-space-ui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        # Reporting API
        location /api/reporting {
            proxy_pass http://eta-flow-space-reporting:8000/api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Web API
        location = /health-check {
            proxy_pass http://eta-flow-space-web-api:3002/health-check;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /sign-in {
            proxy_pass http://eta-flow-space-web-api:3002/sign-in;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /static/flows/ {
            proxy_pass http://eta-flow-space-web-api:3002/static/flows/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /api/ {
            proxy_pass http://eta-flow-space-web-api:3002/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}