events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # UI — served at root
        location / {
            proxy_pass http://eta-flow-space-ui:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Node-RED API
        location /api/ {
            proxy_pass http://eta-flow-space:1880/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Reporting API
        # location /reporting/ {
        #     proxy_pass http://eta-flow-space-reporting:8000/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        # }
    }
}