@baseUrl = http://127.0.0.1:1895

###
@authToken = {{signIn.response.body.token}}

###
# @name signIn
POST {{baseUrl}}/sign-in/
content-type: application/json

{
    "login": "boiler-watcher",
    "password": "0987654321"
}

###
# @name getDeviceState
GET {{baseUrl}}/api/states/device/4
Authorization: Bearer {{authToken}}

###
# @name getDeviceStatesByDateRange
GET {{baseUrl}}/api/states/device/4/dates?beginDate=2026-02-11T00:00:00&endDate=2026-02-11T23:59:59&fields=tempRoomAir;tempOutAir;pressGas;levelDt2;boilers[0].status;networkPumps[3].statusFc
Authorization: Bearer {{authToken}}

###
# @name postDeviceStateValue
POST {{baseUrl}}/api/states/device/1  HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "address": 7,
    "value": true
}

###
# @name getDevices
GET {{baseUrl}}/api/devices
Authorization: Bearer {{authToken}}

###
# @name getDevice
GET {{baseUrl}}/api/devices/4
Authorization: Bearer {{authToken}}

###
# @name getFlows
GET {{baseUrl}}/api/flows
Authorization: Bearer {{authToken}}

###
# @name getMnemoschema
GET {{baseUrl}}/api/mnemoschemas/device/4
Authorization: Bearer {{authToken}}


###
# @name getDataschema
GET {{baseUrl}}/api/data-schemas/device/4
Authorization: Bearer {{authToken}}

###
# @name getQuickHelp1
GET {{baseUrl}}/api/quick-helps/L2NvbW1vbi9pbnRyb2R1Y3Rpb24ubWQ=
Authorization: Bearer {{authToken}}

###
# @name getQuickHelp2
GET {{baseUrl}}/api/quick-helps/Y29tbW9uL2ludHJvZHVjdGlvbg==
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/states/device/4
Authorization: Bearer {{authToken}}

###
GET {{baseUrl}}/api/states/emergency/device/4
Authorization: Bearer {{authToken}}


###
GET {{baseUrl}}/api/states/emergency
Authorization: Bearer {{authToken}}