@baseUrl = http://localhost:3002

###
@authToken = {{signIn.response.body.token}}

###
# @name signIn
POST {{baseUrl}}/sign-in/
content-type: application/json

{
    "login": "admin-boiler-watcher",
    "password": "0987654321"
}

###
# @name getDeviceStatesByDates
GET {{baseUrl}}/api/states/device/4/dates?beginDate=2026-02-11T00:00:00&endDate=2026-02-11T23:59:59&fields=tempRoomAir;tempOutAir;pressGas;levelDt2;boilers[0].status;networkPumps[3].statusFc
Authorization: Bearer {{ authToken }}
