@baseUrl = http://localhost:3002

###
@authToken = {{signIn.response.body.token}}

###
# @name signIn
POST {{baseUrl}}/sign-in/
content-type: application/json

{
    "login": "admin-boiler-watcher",
    "password": "0987654321"
}

###
# @name getDeviceStatesByDates
GET {{baseUrl}}/api/states/device/6/dates?beginDate=2026-04-11T00:00:00Z&endDate=2026-04-11T23:59:59Z&fields=tempRoomAir;tempOutAir;pressGas;levelDt2;boilers[0].status;networkPumps[3].statusFc
Authorization: Bearer {{ authToken }}

###
# @name getEmergencyStatesByDates
GET {{baseUrl}}/api/states/emergency/device/4/dates?beginDate=2026-04-11T00:00:00Z&endDate=2026-04-11T23:59:59Z
Authorization: Bearer {{ authToken }}

###
# @name getFlows
GET {{baseUrl}}/api/flows
Authorization: Bearer {{ authToken }}

###
# @name getDevices
GET {{baseUrl}}/api/devices
Authorization: Bearer {{ authToken }}

###
# @name getDevice
GET {{baseUrl}}/api/devices/1
Authorization: Bearer {{ authToken }}

###
# @name healthCheck
GET {{baseUrl}}/health-check
Authorization: Bearer {{ authToken }}


###
# @name getDeviceMnemoschema
GET {{baseUrl}}/api/devices/4/mnemoschema
Authorization: Bearer {{ authToken }}

###
# @name getDeviceSchema
GET {{baseUrl}}/api/devices/6/data-schema
Authorization: Bearer {{ authToken }}

