FROM node:latest as build

WORKDIR /app

COPY ./ /app/
RUN mkdir -p public && \
    cp -r node_modules/leaflet/dist/images/* public/ || true

RUN npm install --legacy-peer-deps
RUN npm run build

#---------------------------------------
FROM nginx:latest
WORKDIR /app

COPY --from=build /app/dist /app/
COPY --from=build /app/node_modules/leaflet/dist/images/ /app/
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]